/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useLayoutEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import City from '../../../models/starter-scene2.glb'
import * as THREE from 'three'

export default function Model({ ...props }) {

  const { nodes, materials } = useGLTF(City)

  useLayoutEffect(() => {
    Object.values(materials).forEach((material) => {
      material.roughness = 0.2
      // material.stencilWrite = false
    }
      
      )
  }, [])
  
  return (
    <>
    <group {...props} dispose={null}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.main_tv.geometry}
            material={materials["Material.006"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.skyscreaper.geometry}
            material={materials["Material.005"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_1.geometry}
            material={materials.external}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_2.geometry}
            material={materials.Floor}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Areaslanduse.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.lakes.geometry}
            material={materials["Material.007"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane001.geometry}
            material={materials["Material.004"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane002.geometry}
            material={materials["Material.005"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Areasbuilding.geometry}
            material={materials["Material.003"]}
          />
      </group>
    </>
  )
}

useGLTF.preload(City)
